before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: pWXFf6N4kakRLrg4ZLZHLoErKsTvFyL2DFpNd4ce9RkMRZMI9fnWg6doBurnlaOKYK9JOwThKACxDQ1rnKOt1/HCgFbLyWWOle8AvOhL84tzstBGfuTSvWD2VNID106PIFUNMtOeITdzjenAo780M5Z09y2QF/LvdwPmxr1+NmRvW/5X395THL2jSsyH3zbyidh9GWD4kqFz0NR0vPDlMocdv3LRbSfDr63vu5wMNP/Yh5fYam24S7ADj2s7ZOoNhTc2NQcNQ59sNBIbUBLwzWm9I3UGDishR8goTSGw5nmFwT/NvbcL6Jj8rEzyQXFO9vdoNLkN4n+KDRyJOTU9IppTzbAH1fayxOrmJxNk9wzrUgnGGJCa/I5KsqWIBoLqwavwV2mC0EYbeS6E6Yx/cL45kuNgr7npWhMgfL7rDWkd7Zd+SDWsqKjA5BFB0M+zyOSL59RCG5G7msNZpWTLTGJhpHtEkTQb2swEtEeUTyaqpRZGs5wQOuD+mmtkc3eI/4KSAm7fVblRg4g92g5BF27EhpjyoWywhbCamfoLvPR0fGkzSxZHMywVB3Bm1JixcvEuxhI4jN9w2rAQn13RD/QzBY2WtP+dDBhhVO4rfQADG3HBW48yI1RFU3v6Tc0030tkveDx+JwJ8Nxf4ULc9gsONCkLdMMxs3mS8pBoM6w= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
